server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        sub_filter '__SERVER_REPLICA_ID__' '$hostname';
        sub_filter_once on;
    }
}